import DB_query_builder
db = DB_query_builder.query_builder()

'''
db.select('a, b')
db.select_max()
db.select_min()
db.select_avg()
db.select_sum()
db.distinct()
db.from('tabla')
db.from('tabla1, tabla2')
db.where()
db.or_where()
db.where_in()
db.or_where_in()
db.where_not_in()
db.or_where_not_in()
db.like()
db.not_like()
db.or_like()
db.or_not_like()
db.group_start()
db.or_group_start()
db.not_group_start()
db.or_not_group_start()
db.group_end()
db.group_by()
db.having()
db.or_having()
db.order_by()
db.limit()
db.offset()
db.set()
db.get_compiled_select()
db.get()
"""